#/*
# * $RCSfile: Makefile,v $
# * $Revision: 1.3 $
# * $Date: 2000/10/10 00:58:55 $, (c) Copyright 1999 by X.-D. Sheldon Tan
# */

CFLAGS	      = -g -I../inc -I../spinc 

CC	      = gcc

DEST	      = .

HDRS	      =

INSTALL	      = install

LD	      = ld

LDFLAGS	      = -r

LIBS	      = 

MAKEFILE      = Makefile

OBJS	      = pgCircuit.o \
		pgMessage.o \
		pgSens.o \
		pgSysCall.o \
		pgMPS.o \
		pgEquCkt.o \
		pgUtility.o

PRINT	      = pr

PROGRAM       = pgckt.o

SHELL	      = /bin/sh

SRCS	      = pgCircuit.c \
		pgMessage.c \
		pgSens.c \
		pgSysCall.c \
		pgMPS.c \
		pgEquCkt.c \
		pgUtility.c 

all:		$(PROGRAM)

$(PROGRAM):     $(OBJS)  
		@echo "Linking $(PROGRAM) ..."
		@$(LD) $(LDFLAGS) $(OBJS) -o $(PROGRAM) $(LIBS) 
		@echo "done"
		@echo ""

clean:;		@rm -f $(OBJS) core

clobber:;	@rm -f $(OBJS) $(PROGRAM) core tags

depend:;	@makedepend $(CFLAGS) -- $(SRCS)

echo:;		@echo $(HDRS) $(SRCS)

index:;		@ctags -wx $(HDRS) $(SRCS)

install:	$(PROGRAM)
		@echo Installing $(PROGRAM) in $(DEST)
		@-strip $(PROGRAM)
		@if [ $(DEST) != . ]; then \
		(rm -f $(DEST)/$(PROGRAM); $(INSTALL) -f $(DEST) $(PROGRAM)); fi

print:;		@$(PRINT) $(HDRS) $(SRCS)

tags:           $(HDRS) $(SRCS); @ctags $(HDRS) $(SRCS)

update:		$(DEST)/$(PROGRAM)

###
# DO NOT DELETE THIS LINE -- make depend depends on it.

pgCircuit.o: ../inc/pgCircuit.h ../inc/pgCommon.h ../inc/pgStddefs.h
pgCircuit.o: /usr/include/time.h /usr/include/features.h
pgCircuit.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
pgCircuit.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
pgCircuit.o: /usr/include/bits/time.h /usr/include/bits/types.h
pgCircuit.o: ../inc/pgUnixstd.h /usr/include/stdio.h /usr/include/libio.h
pgCircuit.o: /usr/include/_G_config.h /usr/include/wchar.h
pgCircuit.o: /usr/include/bits/wchar.h /usr/include/gconv.h
pgCircuit.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stdarg.h
pgCircuit.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
pgCircuit.o: /usr/include/ctype.h /usr/include/endian.h
pgCircuit.o: /usr/include/bits/endian.h /usr/include/stdlib.h
pgCircuit.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
pgCircuit.o: /usr/include/bits/confname.h /usr/include/errno.h
pgCircuit.o: /usr/include/bits/errno.h /usr/include/linux/errno.h
pgCircuit.o: /usr/include/asm/errno.h /usr/include/assert.h
pgCircuit.o: ../inc/pgUtility.h ../inc/pgMessage.h ../spinc/spmatrix.h
pgCircuit.o: ../spinc/spconfig.h /usr/include/values.h /usr/include/limits.h
pgCircuit.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/limits.h
pgCircuit.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/float.h
pgCircuit.o: ../spinc/sperror.h ../spinc/iferrmsg.h ../spinc/strext.h
pgMessage.o: ../inc/pgUnixstd.h /usr/include/stdio.h /usr/include/features.h
pgMessage.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
pgMessage.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
pgMessage.o: /usr/include/bits/types.h /usr/include/libio.h
pgMessage.o: /usr/include/_G_config.h /usr/include/wchar.h
pgMessage.o: /usr/include/bits/wchar.h /usr/include/gconv.h
pgMessage.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stdarg.h
pgMessage.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
pgMessage.o: /usr/include/ctype.h /usr/include/endian.h
pgMessage.o: /usr/include/bits/endian.h /usr/include/stdlib.h
pgMessage.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
pgMessage.o: /usr/include/bits/confname.h /usr/include/errno.h
pgMessage.o: /usr/include/bits/errno.h /usr/include/linux/errno.h
pgMessage.o: /usr/include/asm/errno.h /usr/include/assert.h
pgMessage.o: ../inc/pgMessage.h
pgSens.o: ../inc/pgCircuit.h ../inc/pgCommon.h ../inc/pgStddefs.h
pgSens.o: /usr/include/time.h /usr/include/features.h
pgSens.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
pgSens.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
pgSens.o: /usr/include/bits/time.h /usr/include/bits/types.h
pgSens.o: ../inc/pgUnixstd.h /usr/include/stdio.h /usr/include/libio.h
pgSens.o: /usr/include/_G_config.h /usr/include/wchar.h
pgSens.o: /usr/include/bits/wchar.h /usr/include/gconv.h
pgSens.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stdarg.h
pgSens.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
pgSens.o: /usr/include/ctype.h /usr/include/endian.h
pgSens.o: /usr/include/bits/endian.h /usr/include/stdlib.h
pgSens.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
pgSens.o: /usr/include/bits/confname.h /usr/include/errno.h
pgSens.o: /usr/include/bits/errno.h /usr/include/linux/errno.h
pgSens.o: /usr/include/asm/errno.h /usr/include/assert.h ../inc/pgUtility.h
pgSens.o: ../inc/pgMessage.h ../spinc/spmatrix.h ../spinc/spconfig.h
pgSens.o: /usr/include/values.h /usr/include/limits.h
pgSens.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/limits.h
pgSens.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/float.h
pgSens.o: ../spinc/sperror.h ../spinc/iferrmsg.h ../spinc/strext.h
pgSens.o: ../inc/pgSens.h
pgSysCall.o: ../inc/pgCommon.h ../inc/pgStddefs.h /usr/include/time.h
pgSysCall.o: /usr/include/features.h /usr/include/sys/cdefs.h
pgSysCall.o: /usr/include/gnu/stubs.h
pgSysCall.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
pgSysCall.o: /usr/include/bits/time.h /usr/include/bits/types.h
pgSysCall.o: ../inc/pgUnixstd.h /usr/include/stdio.h /usr/include/libio.h
pgSysCall.o: /usr/include/_G_config.h /usr/include/wchar.h
pgSysCall.o: /usr/include/bits/wchar.h /usr/include/gconv.h
pgSysCall.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stdarg.h
pgSysCall.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
pgSysCall.o: /usr/include/ctype.h /usr/include/endian.h
pgSysCall.o: /usr/include/bits/endian.h /usr/include/stdlib.h
pgSysCall.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
pgSysCall.o: /usr/include/bits/confname.h /usr/include/errno.h
pgSysCall.o: /usr/include/bits/errno.h /usr/include/linux/errno.h
pgSysCall.o: /usr/include/asm/errno.h /usr/include/assert.h
pgSysCall.o: ../inc/pgUtility.h ../inc/pgMessage.h /usr/include/signal.h
pgSysCall.o: /usr/include/bits/sigset.h /usr/include/bits/signum.h
pgSysCall.o: /usr/include/sys/wait.h /usr/include/sys/resource.h
pgSysCall.o: /usr/include/bits/resource.h /usr/include/bits/waitflags.h
pgSysCall.o: /usr/include/bits/waitstatus.h
pgMPS.o: ../inc/pgMPS.h ../inc/pgCircuit.h ../inc/pgCommon.h
pgMPS.o: ../inc/pgStddefs.h /usr/include/time.h /usr/include/features.h
pgMPS.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
pgMPS.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
pgMPS.o: /usr/include/bits/time.h /usr/include/bits/types.h
pgMPS.o: ../inc/pgUnixstd.h /usr/include/stdio.h /usr/include/libio.h
pgMPS.o: /usr/include/_G_config.h /usr/include/wchar.h
pgMPS.o: /usr/include/bits/wchar.h /usr/include/gconv.h
pgMPS.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stdarg.h
pgMPS.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
pgMPS.o: /usr/include/ctype.h /usr/include/endian.h
pgMPS.o: /usr/include/bits/endian.h /usr/include/stdlib.h
pgMPS.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
pgMPS.o: /usr/include/bits/confname.h /usr/include/errno.h
pgMPS.o: /usr/include/bits/errno.h /usr/include/linux/errno.h
pgMPS.o: /usr/include/asm/errno.h /usr/include/assert.h ../inc/pgUtility.h
pgMPS.o: ../inc/pgMessage.h ../spinc/spmatrix.h ../spinc/spconfig.h
pgMPS.o: /usr/include/values.h /usr/include/limits.h
pgMPS.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/limits.h
pgMPS.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/float.h
pgMPS.o: ../spinc/sperror.h ../spinc/iferrmsg.h ../spinc/strext.h
pgMPS.o: ../inc/pgOptmz.h
pgEquCkt.o: ../inc/pgCircuit.h ../inc/pgCommon.h ../inc/pgStddefs.h
pgEquCkt.o: /usr/include/time.h /usr/include/features.h
pgEquCkt.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
pgEquCkt.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
pgEquCkt.o: /usr/include/bits/time.h /usr/include/bits/types.h
pgEquCkt.o: ../inc/pgUnixstd.h /usr/include/stdio.h /usr/include/libio.h
pgEquCkt.o: /usr/include/_G_config.h /usr/include/wchar.h
pgEquCkt.o: /usr/include/bits/wchar.h /usr/include/gconv.h
pgEquCkt.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stdarg.h
pgEquCkt.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
pgEquCkt.o: /usr/include/ctype.h /usr/include/endian.h
pgEquCkt.o: /usr/include/bits/endian.h /usr/include/stdlib.h
pgEquCkt.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
pgEquCkt.o: /usr/include/bits/confname.h /usr/include/errno.h
pgEquCkt.o: /usr/include/bits/errno.h /usr/include/linux/errno.h
pgEquCkt.o: /usr/include/asm/errno.h /usr/include/assert.h ../inc/pgUtility.h
pgEquCkt.o: ../inc/pgMessage.h ../spinc/spmatrix.h ../spinc/spconfig.h
pgEquCkt.o: /usr/include/values.h /usr/include/limits.h
pgEquCkt.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/limits.h
pgEquCkt.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/float.h
pgEquCkt.o: ../spinc/sperror.h ../spinc/iferrmsg.h ../spinc/strext.h
pgEquCkt.o: ../inc/pgEquCkt.h ../inc/pgOptmz.h
pgUtility.o: ../inc/pgCommon.h ../inc/pgStddefs.h /usr/include/time.h
pgUtility.o: /usr/include/features.h /usr/include/sys/cdefs.h
pgUtility.o: /usr/include/gnu/stubs.h
pgUtility.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
pgUtility.o: /usr/include/bits/time.h /usr/include/bits/types.h
pgUtility.o: ../inc/pgUnixstd.h /usr/include/stdio.h /usr/include/libio.h
pgUtility.o: /usr/include/_G_config.h /usr/include/wchar.h
pgUtility.o: /usr/include/bits/wchar.h /usr/include/gconv.h
pgUtility.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stdarg.h
pgUtility.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
pgUtility.o: /usr/include/ctype.h /usr/include/endian.h
pgUtility.o: /usr/include/bits/endian.h /usr/include/stdlib.h
pgUtility.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
pgUtility.o: /usr/include/bits/confname.h /usr/include/errno.h
pgUtility.o: /usr/include/bits/errno.h /usr/include/linux/errno.h
pgUtility.o: /usr/include/asm/errno.h /usr/include/assert.h
pgUtility.o: ../inc/pgUtility.h ../inc/pgMessage.h /usr/include/math.h
pgUtility.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
pgUtility.o: /usr/include/bits/mathcalls.h /usr/include/sys/types.h
